version: "3.9"

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    restart: always
    command: server --console-address ":9001" /data/
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - storage_net
      - minio_net
    env_file:
      - .env

  createbuckets:
    image: minio/mc
    networks:
      - minio_net
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:${MINIO_PORT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb minio/${MINIO_BUCKET_NAME};
      exit 0;"
    env_file:
      - .env
      #  /usr/bin/mc anonymous set public minio/${MINIO_BUCKET_NAME};

networks:
  minio_net:
  storage_net: