version: "3.9"

services:
  db:
    container_name: postgre
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - meme_net
    ports:
      - '5433:5432'
    env_file:
      - .env

networks:
  meme_net: