FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir -r requirements.txt

RUN sed -i 's/\r$//g' ./entrypoint.sh && \
    chmod +x  ./entrypoint.sh

ENTRYPOINT [ "sh", "./entrypoint.sh" ]

CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port $SERVICE_PORT"]